[settings]
auto_install = false

[tools]
aube = "1.25.1"
node = "26"
npm = ["11", "10"]
pnpm = ["11", "10"]
yarn = ["4"]

[tasks.start-container]
interactive = true
run = "docker compose up -d"

[tasks.setup]
interactive = true
run = "docker compose exec -w /app -it instance mise i && aube i"
raw_args = true

[tasks.test]
interactive = true
run = "docker compose exec -w /app -it instance aube exec vitest run -u"
raw_args = true
